<?php

declare( strict_types = 1 );

namespace Northrook\Symfony\Configurator;

use JetBrains\PhpStorm\Language;
use Northrook\Logger\Log;
use Northrook\Symfony\Console\Output;
use Support\Normalize;
use Symfony\Component\Filesystem\Exception\IOException;
use Symfony\Component\Filesystem\Filesystem;

abstract class AutoConfigure
{
    /** @var bool Has this been instantiated anywhere? */
    private static bool $instantiated = false;

    protected readonly Filesystem $file;
    protected readonly string     $projectDir;

    final public function __construct( string $rootDir )
    {
        $this->projectDir = Normalize::path( $rootDir );

        $this->file = new Filesystem();

        if ( !AutoConfigure::$instantiated ) {
            AutoConfigure::$instantiated = true;
            if ( PHP_SAPI === 'cli' ) {
                Output::init( 'AutoConfigure: Initialized' );
            }
        }
    }

    final protected function path( string $fromProjectDir ) : string
    {
        return Normalize::path( "{$this->projectDir}/{$fromProjectDir}" );
    }

    final protected function removeFile( string $name ) : void
    {
        $path = $this->path( $name );

        if ( !$this->file->exists( $path ) ) {
            return;
        }

        try {
            $this->file->remove( $path );
            Output::info( "AutoConfigure: Removed {$name}." );
        }
        catch ( IOException $e ) {
            $message = "AutoConfigure: Could not remove {$name}. {$e->getMessage()}";
            Log::Error( message : $message, context : [ 'exception' => $e ] );
            Output::error( $message );
        }
    }

    final protected function createFile(
            string $fromProjectDir,
            #[Language( 'PHP' )]
            string $php,
            bool   $overwrite = false,

    ) : void
    {
        $path = $this->path( $fromProjectDir );

        if ( $this->file->exists( $path ) && $overwrite === false ) {
            return;
        }

        $content = $this->parsePhpString( $php );

        try {
            $this->file->dumpFile( $path, $content );
            Output::OK( "AutoConfigure: Generated {$fromProjectDir}." );
        }

        catch
        ( IOException $exception ) {
            $message = "AutoConfigure: Could not generate {$fromProjectDir}. {$exception->getMessage()}";
            Log::Error(
                    message : $message,
                    context : [ 'exception' => $exception, 'path' => $path ],
            );
            Output::error( $message );
        }
    }

    final protected function parsePhpString(
            #[Language( 'PHP' )]
            string $php,
    ) : string
    {
        if ( !\str_starts_with( $php, '<?php' ) ) {
            throw new \UnexpectedValueException(
                    'Autoconfigure was provided a PHP string without an opening tag.',
            );
        }

        $content = \preg_replace(
                pattern     : '#<\?php\s+?(?=\S)#A',
                replacement : "<?php\n\n// Generated by " . $this::class . "\n\n",
                subject     : $php,
        );

        if ( !\is_string( $content ) ) {
            throw new \UnexpectedValueException(
                    'Autoconfigure encountered an unexpected error preparing the PHP string.',
            );
        }
        return $content;
    }

}